//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.RequerimentoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotivoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class MotivoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiposRequerimentoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class TiposRequerimentoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequerimentoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel))]
    public partial class RequerimentoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.RequerimentoService.AlunoModel AlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataPrevistaTerminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.StatusModel> HistoricoDeStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.RequerimentoService.StatusModel StatusAtualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.RequerimentoService.AlunoModel Aluno {
            get {
                return this.AlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlunoField, value) != true)) {
                    this.AlunoField = value;
                    this.RaisePropertyChanged("Aluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAbertura {
            get {
                return this.DataAberturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAberturaField, value) != true)) {
                    this.DataAberturaField = value;
                    this.RaisePropertyChanged("DataAbertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataPrevistaTermino {
            get {
                return this.DataPrevistaTerminoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataPrevistaTerminoField, value) != true)) {
                    this.DataPrevistaTerminoField = value;
                    this.RaisePropertyChanged("DataPrevistaTermino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.StatusModel> HistoricoDeStatus {
            get {
                return this.HistoricoDeStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HistoricoDeStatusField, value) != true)) {
                    this.HistoricoDeStatusField = value;
                    this.RaisePropertyChanged("HistoricoDeStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.RequerimentoService.StatusModel StatusAtual {
            get {
                return this.StatusAtualField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusAtualField, value) != true)) {
                    this.StatusAtualField = value;
                    this.RaisePropertyChanged("StatusAtual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
    [System.SerializableAttribute()]
    public partial class AlunoModel : Solicita.TG.UI.View.RequerimentoService.EntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.RequerimentoService.AlunoModel.MatriculaModel MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.RequerimentoService.AlunoModel.MatriculaModel Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel.MatriculaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
        [System.SerializableAttribute()]
        public partial class MatriculaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AnoIngressoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CargaHoráriaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CursoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PeriodoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RAField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TurnoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AnoIngresso {
                get {
                    return this.AnoIngressoField;
                }
                set {
                    if ((object.ReferenceEquals(this.AnoIngressoField, value) != true)) {
                        this.AnoIngressoField = value;
                        this.RaisePropertyChanged("AnoIngresso");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string CargaHorária {
                get {
                    return this.CargaHoráriaField;
                }
                set {
                    if ((object.ReferenceEquals(this.CargaHoráriaField, value) != true)) {
                        this.CargaHoráriaField = value;
                        this.RaisePropertyChanged("CargaHorária");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Curso {
                get {
                    return this.CursoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                        this.CursoField = value;
                        this.RaisePropertyChanged("Curso");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Periodo {
                get {
                    return this.PeriodoField;
                }
                set {
                    if ((object.ReferenceEquals(this.PeriodoField, value) != true)) {
                        this.PeriodoField = value;
                        this.RaisePropertyChanged("Periodo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RA {
                get {
                    return this.RAField;
                }
                set {
                    if ((object.ReferenceEquals(this.RAField, value) != true)) {
                        this.RAField = value;
                        this.RaisePropertyChanged("RA");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Turno {
                get {
                    return this.TurnoField;
                }
                set {
                    if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                        this.TurnoField = value;
                        this.RaisePropertyChanged("Turno");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class StatusModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataEntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSaidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservaçãoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsávelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataEntrada {
            get {
                return this.DataEntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataEntradaField, value) != true)) {
                    this.DataEntradaField = value;
                    this.RaisePropertyChanged("DataEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSaida {
            get {
                return this.DataSaidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSaidaField, value) != true)) {
                    this.DataSaidaField = value;
                    this.RaisePropertyChanged("DataSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observação {
            get {
                return this.ObservaçãoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservaçãoField, value) != true)) {
                    this.ObservaçãoField = value;
                    this.RaisePropertyChanged("Observação");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Responsável {
            get {
                return this.ResponsávelField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsávelField, value) != true)) {
                    this.ResponsávelField = value;
                    this.RaisePropertyChanged("Responsável");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusNome {
            get {
                return this.StatusNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNomeField, value) != true)) {
                    this.StatusNomeField = value;
                    this.RaisePropertyChanged("StatusNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitacaoDeDocumentosModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class SolicitacaoDeDocumentosModel : Solicita.TG.UI.View.RequerimentoService.RequerimentoModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisciplinaInformadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarAulaAosSabadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarCargaHoráriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarDisciplinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarPeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarPrevisãoDeConclusãoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformarSemestreAtualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoEspecificadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDeMotivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisciplinaInformada {
            get {
                return this.DisciplinaInformadaField;
            }
            set {
                if ((object.ReferenceEquals(this.DisciplinaInformadaField, value) != true)) {
                    this.DisciplinaInformadaField = value;
                    this.RaisePropertyChanged("DisciplinaInformada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarAulaAosSabados {
            get {
                return this.InformarAulaAosSabadosField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarAulaAosSabadosField, value) != true)) {
                    this.InformarAulaAosSabadosField = value;
                    this.RaisePropertyChanged("InformarAulaAosSabados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarCargaHorária {
            get {
                return this.InformarCargaHoráriaField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarCargaHoráriaField, value) != true)) {
                    this.InformarCargaHoráriaField = value;
                    this.RaisePropertyChanged("InformarCargaHorária");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarDisciplina {
            get {
                return this.InformarDisciplinaField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarDisciplinaField, value) != true)) {
                    this.InformarDisciplinaField = value;
                    this.RaisePropertyChanged("InformarDisciplina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarPeriodo {
            get {
                return this.InformarPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarPeriodoField, value) != true)) {
                    this.InformarPeriodoField = value;
                    this.RaisePropertyChanged("InformarPeriodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarPrevisãoDeConclusão {
            get {
                return this.InformarPrevisãoDeConclusãoField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarPrevisãoDeConclusãoField, value) != true)) {
                    this.InformarPrevisãoDeConclusãoField = value;
                    this.RaisePropertyChanged("InformarPrevisãoDeConclusão");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformarSemestreAtual {
            get {
                return this.InformarSemestreAtualField;
            }
            set {
                if ((object.ReferenceEquals(this.InformarSemestreAtualField, value) != true)) {
                    this.InformarSemestreAtualField = value;
                    this.RaisePropertyChanged("InformarSemestreAtual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoEspecificado {
            get {
                return this.MotivoEspecificadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoEspecificadoField, value) != true)) {
                    this.MotivoEspecificadoField = value;
                    this.RaisePropertyChanged("MotivoEspecificado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDeMotivo {
            get {
                return this.TipoDeMotivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeMotivoField, value) != true)) {
                    this.TipoDeMotivoField = value;
                    this.RaisePropertyChanged("TipoDeMotivo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Solicita.TG.UI.View.RequerimentoService.AlunoModel))]
    public partial class EntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequerimentoSimplesModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class RequerimentoSimplesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlunoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataAberturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTerminoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaginaAtualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aluno {
            get {
                return this.AlunoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlunoField, value) != true)) {
                    this.AlunoField = value;
                    this.RaisePropertyChanged("Aluno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataAbertura {
            get {
                return this.DataAberturaField;
            }
            set {
                if ((object.ReferenceEquals(this.DataAberturaField, value) != true)) {
                    this.DataAberturaField = value;
                    this.RaisePropertyChanged("DataAbertura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTermino {
            get {
                return this.DataTerminoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTerminoField, value) != true)) {
                    this.DataTerminoField = value;
                    this.RaisePropertyChanged("DataTermino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPaginas {
            get {
                return this.NumeroPaginasField;
            }
            set {
                if ((this.NumeroPaginasField.Equals(value) != true)) {
                    this.NumeroPaginasField = value;
                    this.RaisePropertyChanged("NumeroPaginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaginaAtual {
            get {
                return this.PaginaAtualField;
            }
            set {
                if ((this.PaginaAtualField.Equals(value) != true)) {
                    this.PaginaAtualField = value;
                    this.RaisePropertyChanged("PaginaAtual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Responsavel {
            get {
                return this.ResponsavelField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsavelField, value) != true)) {
                    this.ResponsavelField = value;
                    this.RaisePropertyChanged("Responsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDeStatusModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Requerimentos.M" +
        "odelos")]
    [System.SerializableAttribute()]
    public partial class TipoDeStatusModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequerimentoService.IRequerimentoService")]
    public interface IRequerimentoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Concluir", ReplyAction="http://tempuri.org/IRequerimentoService/ConcluirResponse")]
        void Concluir(System.Guid id, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Concluir", ReplyAction="http://tempuri.org/IRequerimentoService/ConcluirResponse")]
        System.Threading.Tasks.Task ConcluirAsync(System.Guid id, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarMotivos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarMotivosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.MotivoModel> ListarMotivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarMotivos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarMotivosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.MotivoModel>> ListarMotivosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Indeferir", ReplyAction="http://tempuri.org/IRequerimentoService/IndeferirResponse")]
        void Indeferir(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Indeferir", ReplyAction="http://tempuri.org/IRequerimentoService/IndeferirResponse")]
        System.Threading.Tasks.Task IndeferirAsync(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Cancelar", ReplyAction="http://tempuri.org/IRequerimentoService/CancelarResponse")]
        void Cancelar(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/Cancelar", ReplyAction="http://tempuri.org/IRequerimentoService/CancelarResponse")]
        System.Threading.Tasks.Task CancelarAsync(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/TransferirResponsabilidade", ReplyAction="http://tempuri.org/IRequerimentoService/TransferirResponsabilidadeResponse")]
        void TransferirResponsabilidade(System.Guid id, System.Guid idResponsavel, int tipoResponsavel, string observação);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/TransferirResponsabilidade", ReplyAction="http://tempuri.org/IRequerimentoService/TransferirResponsabilidadeResponse")]
        System.Threading.Tasks.Task TransferirResponsabilidadeAsync(System.Guid id, System.Guid idResponsavel, int tipoResponsavel, string observação);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/CriarSolicitacoesDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/CriarSolicitacoesDeDocumentosResponse")]
        System.Guid CriarSolicitacoesDeDocumentos(System.Guid idAluno, int tipoDoMotivo, int tipoDeDocumento, string especificacaoDoMotivo, bool informarSemestreAtual, bool informarCargaHoraria, bool informarAulaAosSabados, bool informarPrevisaoDeConclusao, bool informarDisciplina, bool informarPeriodo, System.Guid disciplinaInformada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/CriarSolicitacoesDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/CriarSolicitacoesDeDocumentosResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarSolicitacoesDeDocumentosAsync(System.Guid idAluno, int tipoDoMotivo, int tipoDeDocumento, string especificacaoDoMotivo, bool informarSemestreAtual, bool informarCargaHoraria, bool informarAulaAosSabados, bool informarPrevisaoDeConclusao, bool informarDisciplina, bool informarPeriodo, System.Guid disciplinaInformada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTipos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTiposResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TiposRequerimentoModel> ListarTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTipos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTiposResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TiposRequerimentoModel>> ListarTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/GetSolicitacaoDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/GetSolicitacaoDeDocumentosResponse")]
        Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel GetSolicitacaoDeDocumentos(System.Guid idRequerimento, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/GetSolicitacaoDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/GetSolicitacaoDeDocumentosResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel> GetSolicitacaoDeDocumentosAsync(System.Guid idRequerimento, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/List", ReplyAction="http://tempuri.org/IRequerimentoService/ListResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> List(string RA, string nome, System.Guid curso, int periodo, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/List", ReplyAction="http://tempuri.org/IRequerimentoService/ListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListAsync(string RA, string nome, System.Guid curso, int periodo, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListJáAtendidas", ReplyAction="http://tempuri.org/IRequerimentoService/ListJáAtendidasResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListJáAtendidas(string RA, string nome, System.Guid curso, int periodo, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListJáAtendidas", ReplyAction="http://tempuri.org/IRequerimentoService/ListJáAtendidasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListJáAtendidasAsync(string RA, string nome, System.Guid curso, int periodo, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDeDocumentosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel> ListarSolicitacoesDeDocumentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDeDocumentos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDeDocumentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel>> ListarSolicitacoesDeDocumentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarDeclaracoesDeProva", ReplyAction="http://tempuri.org/IRequerimentoService/ListarDeclaracoesDeProvaResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarDeclaracoesDeProva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarDeclaracoesDeProva", ReplyAction="http://tempuri.org/IRequerimentoService/ListarDeclaracoesDeProvaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarDeclaracoesDeProvaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDePasse", ReplyAction="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDePasseResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarSolicitacoesDePasse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDePasse", ReplyAction="http://tempuri.org/IRequerimentoService/ListarSolicitacoesDePasseResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarSolicitacoesDePasseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarReaproveitamentos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarReaproveitamentosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarReaproveitamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarReaproveitamentos", ReplyAction="http://tempuri.org/IRequerimentoService/ListarReaproveitamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarReaproveitamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeCurso", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeCursoResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarTrancamentosDeCurso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeCurso", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeCursoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarTrancamentosDeCursoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeMatricula", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeMatriculaResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarTrancamentosDeMatricula();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeMatricula", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTrancamentosDeMatriculaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarTrancamentosDeMatriculaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTipoDeStatus", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTipoDeStatusResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TipoDeStatusModel> ListarTipoDeStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequerimentoService/ListarTipoDeStatus", ReplyAction="http://tempuri.org/IRequerimentoService/ListarTipoDeStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TipoDeStatusModel>> ListarTipoDeStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequerimentoServiceChannel : Solicita.TG.UI.View.RequerimentoService.IRequerimentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequerimentoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.RequerimentoService.IRequerimentoService>, Solicita.TG.UI.View.RequerimentoService.IRequerimentoService {
        
        public RequerimentoServiceClient() {
        }
        
        public RequerimentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequerimentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequerimentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequerimentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Concluir(System.Guid id, System.Guid idResponsavel, int tipoResponsavel) {
            base.Channel.Concluir(id, idResponsavel, tipoResponsavel);
        }
        
        public System.Threading.Tasks.Task ConcluirAsync(System.Guid id, System.Guid idResponsavel, int tipoResponsavel) {
            return base.Channel.ConcluirAsync(id, idResponsavel, tipoResponsavel);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.MotivoModel> ListarMotivos() {
            return base.Channel.ListarMotivos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.MotivoModel>> ListarMotivosAsync() {
            return base.Channel.ListarMotivosAsync();
        }
        
        public void Indeferir(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel) {
            base.Channel.Indeferir(id, motivo, idResponsavel, tipoResponsavel);
        }
        
        public System.Threading.Tasks.Task IndeferirAsync(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel) {
            return base.Channel.IndeferirAsync(id, motivo, idResponsavel, tipoResponsavel);
        }
        
        public void Cancelar(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel) {
            base.Channel.Cancelar(id, motivo, idResponsavel, tipoResponsavel);
        }
        
        public System.Threading.Tasks.Task CancelarAsync(System.Guid id, string motivo, System.Guid idResponsavel, int tipoResponsavel) {
            return base.Channel.CancelarAsync(id, motivo, idResponsavel, tipoResponsavel);
        }
        
        public void TransferirResponsabilidade(System.Guid id, System.Guid idResponsavel, int tipoResponsavel, string observação) {
            base.Channel.TransferirResponsabilidade(id, idResponsavel, tipoResponsavel, observação);
        }
        
        public System.Threading.Tasks.Task TransferirResponsabilidadeAsync(System.Guid id, System.Guid idResponsavel, int tipoResponsavel, string observação) {
            return base.Channel.TransferirResponsabilidadeAsync(id, idResponsavel, tipoResponsavel, observação);
        }
        
        public System.Guid CriarSolicitacoesDeDocumentos(System.Guid idAluno, int tipoDoMotivo, int tipoDeDocumento, string especificacaoDoMotivo, bool informarSemestreAtual, bool informarCargaHoraria, bool informarAulaAosSabados, bool informarPrevisaoDeConclusao, bool informarDisciplina, bool informarPeriodo, System.Guid disciplinaInformada) {
            return base.Channel.CriarSolicitacoesDeDocumentos(idAluno, tipoDoMotivo, tipoDeDocumento, especificacaoDoMotivo, informarSemestreAtual, informarCargaHoraria, informarAulaAosSabados, informarPrevisaoDeConclusao, informarDisciplina, informarPeriodo, disciplinaInformada);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarSolicitacoesDeDocumentosAsync(System.Guid idAluno, int tipoDoMotivo, int tipoDeDocumento, string especificacaoDoMotivo, bool informarSemestreAtual, bool informarCargaHoraria, bool informarAulaAosSabados, bool informarPrevisaoDeConclusao, bool informarDisciplina, bool informarPeriodo, System.Guid disciplinaInformada) {
            return base.Channel.CriarSolicitacoesDeDocumentosAsync(idAluno, tipoDoMotivo, tipoDeDocumento, especificacaoDoMotivo, informarSemestreAtual, informarCargaHoraria, informarAulaAosSabados, informarPrevisaoDeConclusao, informarDisciplina, informarPeriodo, disciplinaInformada);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TiposRequerimentoModel> ListarTipos() {
            return base.Channel.ListarTipos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TiposRequerimentoModel>> ListarTiposAsync() {
            return base.Channel.ListarTiposAsync();
        }
        
        public Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel GetSolicitacaoDeDocumentos(System.Guid idRequerimento, string type) {
            return base.Channel.GetSolicitacaoDeDocumentos(idRequerimento, type);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel> GetSolicitacaoDeDocumentosAsync(System.Guid idRequerimento, string type) {
            return base.Channel.GetSolicitacaoDeDocumentosAsync(idRequerimento, type);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> List(string RA, string nome, System.Guid curso, int periodo, string type) {
            return base.Channel.List(RA, nome, curso, periodo, type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListAsync(string RA, string nome, System.Guid curso, int periodo, string type) {
            return base.Channel.ListAsync(RA, nome, curso, periodo, type);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListJáAtendidas(string RA, string nome, System.Guid curso, int periodo, string type) {
            return base.Channel.ListJáAtendidas(RA, nome, curso, periodo, type);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListJáAtendidasAsync(string RA, string nome, System.Guid curso, int periodo, string type) {
            return base.Channel.ListJáAtendidasAsync(RA, nome, curso, periodo, type);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel> ListarSolicitacoesDeDocumentos() {
            return base.Channel.ListarSolicitacoesDeDocumentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.SolicitacaoDeDocumentosModel>> ListarSolicitacoesDeDocumentosAsync() {
            return base.Channel.ListarSolicitacoesDeDocumentosAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarDeclaracoesDeProva() {
            return base.Channel.ListarDeclaracoesDeProva();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarDeclaracoesDeProvaAsync() {
            return base.Channel.ListarDeclaracoesDeProvaAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarSolicitacoesDePasse() {
            return base.Channel.ListarSolicitacoesDePasse();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarSolicitacoesDePasseAsync() {
            return base.Channel.ListarSolicitacoesDePasseAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarReaproveitamentos() {
            return base.Channel.ListarReaproveitamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarReaproveitamentosAsync() {
            return base.Channel.ListarReaproveitamentosAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarTrancamentosDeCurso() {
            return base.Channel.ListarTrancamentosDeCurso();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarTrancamentosDeCursoAsync() {
            return base.Channel.ListarTrancamentosDeCursoAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel> ListarTrancamentosDeMatricula() {
            return base.Channel.ListarTrancamentosDeMatricula();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.RequerimentoSimplesModel>> ListarTrancamentosDeMatriculaAsync() {
            return base.Channel.ListarTrancamentosDeMatriculaAsync();
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TipoDeStatusModel> ListarTipoDeStatus() {
            return base.Channel.ListarTipoDeStatus();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.RequerimentoService.TipoDeStatusModel>> ListarTipoDeStatusAsync() {
            return base.Channel.ListarTipoDeStatusAsync();
        }
    }
}
