//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.CursoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Solicita.TG.UI.View.CursoService.CursoModel))]
    public partial class EntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.cursoService.Mo" +
        "delos")]
    [System.SerializableAttribute()]
    public partial class CursoModel : Solicita.TG.UI.View.CursoService.EntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CargaHorariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.DisciplinaModel> GradeCurricularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CargaHoraria {
            get {
                return this.CargaHorariaField;
            }
            set {
                if ((this.CargaHorariaField.Equals(value) != true)) {
                    this.CargaHorariaField = value;
                    this.RaisePropertyChanged("CargaHoraria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.DisciplinaModel> GradeCurricular {
            get {
                return this.GradeCurricularField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeCurricularField, value) != true)) {
                    this.GradeCurricularField = value;
                    this.RaisePropertyChanged("GradeCurricular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisciplinaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.DisciplinaServi" +
        "ce.Modelos")]
    [System.SerializableAttribute()]
    public partial class DisciplinaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CargaHorariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CargaHoraria {
            get {
                return this.CargaHorariaField;
            }
            set {
                if ((this.CargaHorariaField.Equals(value) != true)) {
                    this.CargaHorariaField = value;
                    this.RaisePropertyChanged("CargaHoraria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CursoService.ICursoService")]
    public interface ICursoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Criar", ReplyAction="http://tempuri.org/ICursoService/CriarResponse")]
        System.Guid Criar(string nome, System.Collections.Generic.List<System.Guid> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Criar", ReplyAction="http://tempuri.org/ICursoService/CriarResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarAsync(string nome, System.Collections.Generic.List<System.Guid> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Get", ReplyAction="http://tempuri.org/ICursoService/GetResponse")]
        Solicita.TG.UI.View.CursoService.CursoModel Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Get", ReplyAction="http://tempuri.org/ICursoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.CursoService.CursoModel> GetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Listar", ReplyAction="http://tempuri.org/ICursoService/ListarResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel> Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Listar", ReplyAction="http://tempuri.org/ICursoService/ListarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel>> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Excluir", ReplyAction="http://tempuri.org/ICursoService/ExcluirResponse")]
        void Excluir(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Excluir", ReplyAction="http://tempuri.org/ICursoService/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/ListarCursosDoAluno", ReplyAction="http://tempuri.org/ICursoService/ListarCursosDoAlunoResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel> ListarCursosDoAluno(System.Guid idAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/ListarCursosDoAluno", ReplyAction="http://tempuri.org/ICursoService/ListarCursosDoAlunoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel>> ListarCursosDoAlunoAsync(System.Guid idAluno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Salvar", ReplyAction="http://tempuri.org/ICursoService/SalvarResponse")]
        void Salvar(System.Guid id, string nome, System.Collections.Generic.List<System.Guid> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Salvar", ReplyAction="http://tempuri.org/ICursoService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(System.Guid id, string nome, System.Collections.Generic.List<System.Guid> idDisciplinas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoServiceChannel : Solicita.TG.UI.View.CursoService.ICursoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.CursoService.ICursoService>, Solicita.TG.UI.View.CursoService.ICursoService {
        
        public CursoServiceClient() {
        }
        
        public CursoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Criar(string nome, System.Collections.Generic.List<System.Guid> idDisciplinas) {
            return base.Channel.Criar(nome, idDisciplinas);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarAsync(string nome, System.Collections.Generic.List<System.Guid> idDisciplinas) {
            return base.Channel.CriarAsync(nome, idDisciplinas);
        }
        
        public Solicita.TG.UI.View.CursoService.CursoModel Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.CursoService.CursoModel> GetAsync(System.Guid id) {
            return base.Channel.GetAsync(id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel> Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel>> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public void Excluir(System.Guid id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(System.Guid id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel> ListarCursosDoAluno(System.Guid idAluno) {
            return base.Channel.ListarCursosDoAluno(idAluno);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.CursoService.CursoModel>> ListarCursosDoAlunoAsync(System.Guid idAluno) {
            return base.Channel.ListarCursosDoAlunoAsync(idAluno);
        }
        
        public void Salvar(System.Guid id, string nome, System.Collections.Generic.List<System.Guid> idDisciplinas) {
            base.Channel.Salvar(id, nome, idDisciplinas);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(System.Guid id, string nome, System.Collections.Generic.List<System.Guid> idDisciplinas) {
            return base.Channel.SalvarAsync(id, nome, idDisciplinas);
        }
    }
}
