//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.DisciplinaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Solicita.TG.UI.View.DisciplinaService.DisciplinaModel))]
    public partial class EntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisciplinaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.DisciplinaServi" +
        "ce.Modelos")]
    [System.SerializableAttribute()]
    public partial class DisciplinaModel : Solicita.TG.UI.View.DisciplinaService.EntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CargaHorariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CargaHoraria {
            get {
                return this.CargaHorariaField;
            }
            set {
                if ((this.CargaHorariaField.Equals(value) != true)) {
                    this.CargaHorariaField = value;
                    this.RaisePropertyChanged("CargaHoraria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DisciplinaService.IDisciplinaService")]
    public interface IDisciplinaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Criar", ReplyAction="http://tempuri.org/IDisciplinaService/CriarResponse")]
        System.Guid Criar(string nome, int cargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Criar", ReplyAction="http://tempuri.org/IDisciplinaService/CriarResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarAsync(string nome, int cargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Get", ReplyAction="http://tempuri.org/IDisciplinaService/GetResponse")]
        Solicita.TG.UI.View.DisciplinaService.DisciplinaModel Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Get", ReplyAction="http://tempuri.org/IDisciplinaService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> GetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Listar", ReplyAction="http://tempuri.org/IDisciplinaService/ListarResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Listar", ReplyAction="http://tempuri.org/IDisciplinaService/ListarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel>> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Excluir", ReplyAction="http://tempuri.org/IDisciplinaService/ExcluirResponse")]
        void Excluir(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Excluir", ReplyAction="http://tempuri.org/IDisciplinaService/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Salvar", ReplyAction="http://tempuri.org/IDisciplinaService/SalvarResponse")]
        void Salvar(System.Guid id, string novoNome, int novaCargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Salvar", ReplyAction="http://tempuri.org/IDisciplinaService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(System.Guid id, string novoNome, int novaCargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/ListarDisciplinasPorNome", ReplyAction="http://tempuri.org/IDisciplinaService/ListarDisciplinasPorNomeResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> ListarDisciplinasPorNome(string nome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/ListarDisciplinasPorNome", ReplyAction="http://tempuri.org/IDisciplinaService/ListarDisciplinasPorNomeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel>> ListarDisciplinasPorNomeAsync(string nome);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDisciplinaServiceChannel : Solicita.TG.UI.View.DisciplinaService.IDisciplinaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisciplinaServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.DisciplinaService.IDisciplinaService>, Solicita.TG.UI.View.DisciplinaService.IDisciplinaService {
        
        public DisciplinaServiceClient() {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisciplinaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Criar(string nome, int cargaHoraria) {
            return base.Channel.Criar(nome, cargaHoraria);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarAsync(string nome, int cargaHoraria) {
            return base.Channel.CriarAsync(nome, cargaHoraria);
        }
        
        public Solicita.TG.UI.View.DisciplinaService.DisciplinaModel Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> GetAsync(System.Guid id) {
            return base.Channel.GetAsync(id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel>> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public void Excluir(System.Guid id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(System.Guid id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public void Salvar(System.Guid id, string novoNome, int novaCargaHoraria) {
            base.Channel.Salvar(id, novoNome, novaCargaHoraria);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(System.Guid id, string novoNome, int novaCargaHoraria) {
            return base.Channel.SalvarAsync(id, novoNome, novaCargaHoraria);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel> ListarDisciplinasPorNome(string nome) {
            return base.Channel.ListarDisciplinasPorNome(nome);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.DisciplinaService.DisciplinaModel>> ListarDisciplinasPorNomeAsync(string nome) {
            return base.Channel.ListarDisciplinasPorNomeAsync(nome);
        }
    }
}
