//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.ProfessorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfessorModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Professor.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class ProfessorModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CordenadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cordenador {
            get {
                return this.CordenadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CordenadorField, value) != true)) {
                    this.CordenadorField = value;
                    this.RaisePropertyChanged("Cordenador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfessorService.IProfessorService")]
    public interface IProfessorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/CriarProfessor", ReplyAction="http://tempuri.org/IProfessorService/CriarProfessorResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.ProfessorService.MyServiceFault), Action="http://tempuri.org/IProfessorService/CriarProfessorMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        System.Guid CriarProfessor(string Nome, string Sobrenome, bool Cordenador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/CriarProfessor", ReplyAction="http://tempuri.org/IProfessorService/CriarProfessorResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarProfessorAsync(string Nome, string Sobrenome, bool Cordenador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/ListarTodosProfessores", ReplyAction="http://tempuri.org/IProfessorService/ListarTodosProfessoresResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.ProfessorService.ProfessorModel> ListarTodosProfessores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/ListarTodosProfessores", ReplyAction="http://tempuri.org/IProfessorService/ListarTodosProfessoresResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.ProfessorService.ProfessorModel>> ListarTodosProfessoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/Get", ReplyAction="http://tempuri.org/IProfessorService/GetResponse")]
        Solicita.TG.UI.ProfessorService.ProfessorModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfessorService/Get", ReplyAction="http://tempuri.org/IProfessorService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.ProfessorService.ProfessorModel> GetAsync(System.Guid Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfessorServiceChannel : Solicita.TG.UI.ProfessorService.IProfessorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfessorServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.ProfessorService.IProfessorService>, Solicita.TG.UI.ProfessorService.IProfessorService {
        
        public ProfessorServiceClient() {
        }
        
        public ProfessorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfessorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfessorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarProfessor(string Nome, string Sobrenome, bool Cordenador) {
            return base.Channel.CriarProfessor(Nome, Sobrenome, Cordenador);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarProfessorAsync(string Nome, string Sobrenome, bool Cordenador) {
            return base.Channel.CriarProfessorAsync(Nome, Sobrenome, Cordenador);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.ProfessorService.ProfessorModel> ListarTodosProfessores() {
            return base.Channel.ListarTodosProfessores();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.ProfessorService.ProfessorModel>> ListarTodosProfessoresAsync() {
            return base.Channel.ListarTodosProfessoresAsync();
        }
        
        public Solicita.TG.UI.ProfessorService.ProfessorModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.ProfessorService.ProfessorModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
    }
}
