//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.AlunoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
    [System.SerializableAttribute()]
    public partial class AlunoModel : Solicita.TG.UI.View.AlunoService.EntityModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EditavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.AlunoService.AlunoModel.MatriculaModel MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Editavel {
            get {
                return this.EditavelField;
            }
            set {
                if ((this.EditavelField.Equals(value) != true)) {
                    this.EditavelField = value;
                    this.RaisePropertyChanged("Editavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.AlunoService.AlunoModel.MatriculaModel Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel.MatriculaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
        [System.SerializableAttribute()]
        public partial class MatriculaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string AnoIngressoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CargaHoráriaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string CursoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PeriodoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RAField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TurnoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string AnoIngresso {
                get {
                    return this.AnoIngressoField;
                }
                set {
                    if ((object.ReferenceEquals(this.AnoIngressoField, value) != true)) {
                        this.AnoIngressoField = value;
                        this.RaisePropertyChanged("AnoIngresso");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string CargaHorária {
                get {
                    return this.CargaHoráriaField;
                }
                set {
                    if ((object.ReferenceEquals(this.CargaHoráriaField, value) != true)) {
                        this.CargaHoráriaField = value;
                        this.RaisePropertyChanged("CargaHorária");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Curso {
                get {
                    return this.CursoField;
                }
                set {
                    if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                        this.CursoField = value;
                        this.RaisePropertyChanged("Curso");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Periodo {
                get {
                    return this.PeriodoField;
                }
                set {
                    if ((object.ReferenceEquals(this.PeriodoField, value) != true)) {
                        this.PeriodoField = value;
                        this.RaisePropertyChanged("Periodo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RA {
                get {
                    return this.RAField;
                }
                set {
                    if ((object.ReferenceEquals(this.RAField, value) != true)) {
                        this.RAField = value;
                        this.RaisePropertyChanged("RA");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Turno {
                get {
                    return this.TurnoField;
                }
                set {
                    if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                        this.TurnoField = value;
                        this.RaisePropertyChanged("Turno");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Solicita.TG.UI.View.AlunoService.AlunoModel))]
    public partial class EntityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlunoService.IAlunoService")]
    public interface IAlunoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Criar", ReplyAction="http://tempuri.org/IAlunoService/CriarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.View.AlunoService.MyServiceFault), Action="http://tempuri.org/IAlunoService/CriarMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        void Criar(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Criar", ReplyAction="http://tempuri.org/IAlunoService/CriarResponse")]
        System.Threading.Tasks.Task CriarAsync(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Listar", ReplyAction="http://tempuri.org/IAlunoService/ListarResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.AlunoService.AlunoModel> Listar(string RA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Listar", ReplyAction="http://tempuri.org/IAlunoService/ListarResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AlunoService.AlunoModel>> ListarAsync(string RA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Salvar", ReplyAction="http://tempuri.org/IAlunoService/SalvarResponse")]
        void Salvar(System.Guid Id, string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Salvar", ReplyAction="http://tempuri.org/IAlunoService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(System.Guid Id, string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Get", ReplyAction="http://tempuri.org/IAlunoService/GetResponse")]
        Solicita.TG.UI.View.AlunoService.AlunoModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Get", ReplyAction="http://tempuri.org/IAlunoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AlunoService.AlunoModel> GetAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetByRA", ReplyAction="http://tempuri.org/IAlunoService/GetByRAResponse")]
        Solicita.TG.UI.View.AlunoService.AlunoModel GetByRA(string RA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/GetByRA", ReplyAction="http://tempuri.org/IAlunoService/GetByRAResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AlunoService.AlunoModel> GetByRAAsync(string RA);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlunoServiceChannel : Solicita.TG.UI.View.AlunoService.IAlunoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlunoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.AlunoService.IAlunoService>, Solicita.TG.UI.View.AlunoService.IAlunoService {
        
        public AlunoServiceClient() {
        }
        
        public AlunoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Criar(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso) {
            base.Channel.Criar(Nome, Sobrenome, RA, RG, Periodo, Turno, Curso);
        }
        
        public System.Threading.Tasks.Task CriarAsync(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso) {
            return base.Channel.CriarAsync(Nome, Sobrenome, RA, RG, Periodo, Turno, Curso);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.AlunoService.AlunoModel> Listar(string RA) {
            return base.Channel.Listar(RA);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AlunoService.AlunoModel>> ListarAsync(string RA) {
            return base.Channel.ListarAsync(RA);
        }
        
        public void Salvar(System.Guid Id, string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso) {
            base.Channel.Salvar(Id, Nome, Sobrenome, RA, RG, Periodo, Turno, Curso);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(System.Guid Id, string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno, System.Guid Curso) {
            return base.Channel.SalvarAsync(Id, Nome, Sobrenome, RA, RG, Periodo, Turno, Curso);
        }
        
        public Solicita.TG.UI.View.AlunoService.AlunoModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AlunoService.AlunoModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public Solicita.TG.UI.View.AlunoService.AlunoModel GetByRA(string RA) {
            return base.Channel.GetByRA(RA);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AlunoService.AlunoModel> GetByRAAsync(string RA) {
            return base.Channel.GetByRAAsync(RA);
        }
    }
}
