//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.DashboardService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolumetriaAnual", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class VolumetriaAnual : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.DashboardService.VolumetriaAnualChartData[] ChartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] MesesNoPeriodoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.DashboardService.VolumetriaAnualChartData[] Chart {
            get {
                return this.ChartField;
            }
            set {
                if ((object.ReferenceEquals(this.ChartField, value) != true)) {
                    this.ChartField = value;
                    this.RaisePropertyChanged("Chart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] MesesNoPeriodo {
            get {
                return this.MesesNoPeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.MesesNoPeriodoField, value) != true)) {
                    this.MesesNoPeriodoField = value;
                    this.RaisePropertyChanged("MesesNoPeriodo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolumetriaAnualChartData", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class VolumetriaAnualChartData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelDate {
            get {
                return this.LabelDateField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelDateField, value) != true)) {
                    this.LabelDateField = value;
                    this.RaisePropertyChanged("LabelDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolumetriaMensalModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class VolumetriaMensalModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.DashboardService.VolumetriaMensalPorCategoriaModel[] VolumetriaPorMesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.DashboardService.VolumetriaMensalPorCategoriaModel[] VolumetriaPorMes {
            get {
                return this.VolumetriaPorMesField;
            }
            set {
                if ((object.ReferenceEquals(this.VolumetriaPorMesField, value) != true)) {
                    this.VolumetriaPorMesField = value;
                    this.RaisePropertyChanged("VolumetriaPorMes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VolumetriaMensalPorCategoriaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class VolumetriaMensalPorCategoriaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomDashBoardModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class CustomDashBoardModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountPorTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountPorTipo {
            get {
                return this.CountPorTipoField;
            }
            set {
                if ((this.CountPorTipoField.Equals(value) != true)) {
                    this.CountPorTipoField = value;
                    this.RaisePropertyChanged("CountPorTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumoAtual", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Dashboard.Model" +
        "os")]
    [System.SerializableAttribute()]
    public partial class ResumoAtual : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MediaConclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeEmAndamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MediaConclusao {
            get {
                return this.MediaConclusaoField;
            }
            set {
                if ((this.MediaConclusaoField.Equals(value) != true)) {
                    this.MediaConclusaoField = value;
                    this.RaisePropertyChanged("MediaConclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantidadeEmAndamento {
            get {
                return this.QuantidadeEmAndamentoField;
            }
            set {
                if ((this.QuantidadeEmAndamentoField.Equals(value) != true)) {
                    this.QuantidadeEmAndamentoField = value;
                    this.RaisePropertyChanged("QuantidadeEmAndamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DashboardService.IDashboardService")]
    public interface IDashboardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaAnual", ReplyAction="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaAnualResponse")]
        Solicita.TG.UI.View.DashboardService.VolumetriaAnual CriarGraficoDeVolumetriaAnual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaAnual", ReplyAction="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaAnualResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.VolumetriaAnual> CriarGraficoDeVolumetriaAnualAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaMensal", ReplyAction="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaMensalResponse")]
        Solicita.TG.UI.View.DashboardService.VolumetriaMensalModel CriarGraficoDeVolumetriaMensal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaMensal", ReplyAction="http://tempuri.org/IDashboardService/CriarGraficoDeVolumetriaMensalResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.VolumetriaMensalModel> CriarGraficoDeVolumetriaMensalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/GraficoQuantidadePorTipo", ReplyAction="http://tempuri.org/IDashboardService/GraficoQuantidadePorTipoResponse")]
        Solicita.TG.UI.View.DashboardService.CustomDashBoardModel[] GraficoQuantidadePorTipo(int[] status, System.Guid aluno, System.Guid responsavel, bool agruparPorTipo, System.Guid Disciplina, string dataInicial, string dataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/GraficoQuantidadePorTipo", ReplyAction="http://tempuri.org/IDashboardService/GraficoQuantidadePorTipoResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.CustomDashBoardModel[]> GraficoQuantidadePorTipoAsync(int[] status, System.Guid aluno, System.Guid responsavel, bool agruparPorTipo, System.Guid Disciplina, string dataInicial, string dataFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/ResumoAtual", ReplyAction="http://tempuri.org/IDashboardService/ResumoAtualResponse")]
        Solicita.TG.UI.View.DashboardService.ResumoAtual ResumoAtual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDashboardService/ResumoAtual", ReplyAction="http://tempuri.org/IDashboardService/ResumoAtualResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.ResumoAtual> ResumoAtualAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDashboardServiceChannel : Solicita.TG.UI.View.DashboardService.IDashboardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DashboardServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.DashboardService.IDashboardService>, Solicita.TG.UI.View.DashboardService.IDashboardService {
        
        public DashboardServiceClient() {
        }
        
        public DashboardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DashboardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DashboardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Solicita.TG.UI.View.DashboardService.VolumetriaAnual CriarGraficoDeVolumetriaAnual() {
            return base.Channel.CriarGraficoDeVolumetriaAnual();
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.VolumetriaAnual> CriarGraficoDeVolumetriaAnualAsync() {
            return base.Channel.CriarGraficoDeVolumetriaAnualAsync();
        }
        
        public Solicita.TG.UI.View.DashboardService.VolumetriaMensalModel CriarGraficoDeVolumetriaMensal() {
            return base.Channel.CriarGraficoDeVolumetriaMensal();
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.VolumetriaMensalModel> CriarGraficoDeVolumetriaMensalAsync() {
            return base.Channel.CriarGraficoDeVolumetriaMensalAsync();
        }
        
        public Solicita.TG.UI.View.DashboardService.CustomDashBoardModel[] GraficoQuantidadePorTipo(int[] status, System.Guid aluno, System.Guid responsavel, bool agruparPorTipo, System.Guid Disciplina, string dataInicial, string dataFinal) {
            return base.Channel.GraficoQuantidadePorTipo(status, aluno, responsavel, agruparPorTipo, Disciplina, dataInicial, dataFinal);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.CustomDashBoardModel[]> GraficoQuantidadePorTipoAsync(int[] status, System.Guid aluno, System.Guid responsavel, bool agruparPorTipo, System.Guid Disciplina, string dataInicial, string dataFinal) {
            return base.Channel.GraficoQuantidadePorTipoAsync(status, aluno, responsavel, agruparPorTipo, Disciplina, dataInicial, dataFinal);
        }
        
        public Solicita.TG.UI.View.DashboardService.ResumoAtual ResumoAtual() {
            return base.Channel.ResumoAtual();
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.DashboardService.ResumoAtual> ResumoAtualAsync() {
            return base.Channel.ResumoAtualAsync();
        }
    }
}
