//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.View.AcessoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioLogado", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class UsuarioLogado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoValue {
            get {
                return this.TipoValueField;
            }
            set {
                if ((this.TipoValueField.Equals(value) != true)) {
                    this.TipoValueField = value;
                    this.RaisePropertyChanged("TipoValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcessoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class AcessoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuario {
            get {
                return this.TipoDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeUsuarioField, value) != true)) {
                    this.TipoDeUsuarioField = value;
                    this.RaisePropertyChanged("TipoDeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AcessoModel.TipoDeUsuarioModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
        [System.SerializableAttribute()]
        public partial class TipoDeUsuarioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NomeDoTipoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int TipoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string NomeDoTipo {
                get {
                    return this.NomeDoTipoField;
                }
                set {
                    if ((object.ReferenceEquals(this.NomeDoTipoField, value) != true)) {
                        this.NomeDoTipoField = value;
                        this.RaisePropertyChanged("NomeDoTipo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Tipo {
                get {
                    return this.TipoField;
                }
                set {
                    if ((this.TipoField.Equals(value) != true)) {
                        this.TipoField = value;
                        this.RaisePropertyChanged("Tipo");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoDeLogon", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class InfoDeLogon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AcessoLiberadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeDoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.View.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcessoLiberado {
            get {
                return this.AcessoLiberadoField;
            }
            set {
                if ((this.AcessoLiberadoField.Equals(value) != true)) {
                    this.AcessoLiberadoField = value;
                    this.RaisePropertyChanged("AcessoLiberado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeDoUsuario {
            get {
                return this.NomeDoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeDoUsuarioField, value) != true)) {
                    this.NomeDoUsuarioField = value;
                    this.RaisePropertyChanged("NomeDoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.View.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuario {
            get {
                return this.TipoDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeUsuarioField, value) != true)) {
                    this.TipoDeUsuarioField = value;
                    this.RaisePropertyChanged("TipoDeUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TiposModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class TiposModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcessoService.IAcessoService")]
    public interface IAcessoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/CriarAcesso", ReplyAction="http://tempuri.org/IAcessoService/CriarAcessoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.View.AcessoService.MyServiceFault), Action="http://tempuri.org/IAcessoService/CriarAcessoMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        System.Guid CriarAcesso(System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/CriarAcesso", ReplyAction="http://tempuri.org/IAcessoService/CriarAcessoResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarAcessoAsync(System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/SalvarAcesso", ReplyAction="http://tempuri.org/IAcessoService/SalvarAcessoResponse")]
        void SalvarAcesso(System.Guid Id, System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/SalvarAcesso", ReplyAction="http://tempuri.org/IAcessoService/SalvarAcessoResponse")]
        System.Threading.Tasks.Task SalvarAcessoAsync(System.Guid Id, System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/BuscarUsuarioLogado", ReplyAction="http://tempuri.org/IAcessoService/BuscarUsuarioLogadoResponse")]
        Solicita.TG.UI.View.AcessoService.UsuarioLogado BuscarUsuarioLogado(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/BuscarUsuarioLogado", ReplyAction="http://tempuri.org/IAcessoService/BuscarUsuarioLogadoResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.UsuarioLogado> BuscarUsuarioLogadoAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTodosAcessos", ReplyAction="http://tempuri.org/IAcessoService/ListarTodosAcessosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.AcessoModel> ListarTodosAcessos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTodosAcessos", ReplyAction="http://tempuri.org/IAcessoService/ListarTodosAcessosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.AcessoModel>> ListarTodosAcessosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Get", ReplyAction="http://tempuri.org/IAcessoService/GetResponse")]
        Solicita.TG.UI.View.AcessoService.AcessoModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Get", ReplyAction="http://tempuri.org/IAcessoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.AcessoModel> GetAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/AlterarSenha", ReplyAction="http://tempuri.org/IAcessoService/AlterarSenhaResponse")]
        void AlterarSenha(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/AlterarSenha", ReplyAction="http://tempuri.org/IAcessoService/AlterarSenhaResponse")]
        System.Threading.Tasks.Task AlterarSenhaAsync(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Login", ReplyAction="http://tempuri.org/IAcessoService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.View.AcessoService.MyServiceFault), Action="http://tempuri.org/IAcessoService/LoginMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        Solicita.TG.UI.View.AcessoService.InfoDeLogon Login(string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Login", ReplyAction="http://tempuri.org/IAcessoService/LoginResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.InfoDeLogon> LoginAsync(string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTipos", ReplyAction="http://tempuri.org/IAcessoService/ListarTiposResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.TiposModel> ListarTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTipos", ReplyAction="http://tempuri.org/IAcessoService/ListarTiposResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.TiposModel>> ListarTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/LogarComoALuno", ReplyAction="http://tempuri.org/IAcessoService/LogarComoALunoResponse")]
        Solicita.TG.UI.View.AcessoService.InfoDeLogon LogarComoALuno(string RA, string RG, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/LogarComoALuno", ReplyAction="http://tempuri.org/IAcessoService/LogarComoALunoResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.InfoDeLogon> LogarComoALunoAsync(string RA, string RG, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/RecuperarSenha", ReplyAction="http://tempuri.org/IAcessoService/RecuperarSenhaResponse")]
        bool RecuperarSenha(string RA, string RG, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/RecuperarSenha", ReplyAction="http://tempuri.org/IAcessoService/RecuperarSenhaResponse")]
        System.Threading.Tasks.Task<bool> RecuperarSenhaAsync(string RA, string RG, string Email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcessoServiceChannel : Solicita.TG.UI.View.AcessoService.IAcessoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcessoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.View.AcessoService.IAcessoService>, Solicita.TG.UI.View.AcessoService.IAcessoService {
        
        public AcessoServiceClient() {
        }
        
        public AcessoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcessoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcessoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcessoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarAcesso(System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.CriarAcesso(IdEntidadeAssociada, Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarAcessoAsync(System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.CriarAcessoAsync(IdEntidadeAssociada, Usuario, Senha, TipoDeUsuario);
        }
        
        public void SalvarAcesso(System.Guid Id, System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario) {
            base.Channel.SalvarAcesso(Id, IdEntidadeAssociada, Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Threading.Tasks.Task SalvarAcessoAsync(System.Guid Id, System.Guid IdEntidadeAssociada, string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.SalvarAcessoAsync(Id, IdEntidadeAssociada, Usuario, Senha, TipoDeUsuario);
        }
        
        public Solicita.TG.UI.View.AcessoService.UsuarioLogado BuscarUsuarioLogado(string usuario) {
            return base.Channel.BuscarUsuarioLogado(usuario);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.UsuarioLogado> BuscarUsuarioLogadoAsync(string usuario) {
            return base.Channel.BuscarUsuarioLogadoAsync(usuario);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.AcessoModel> ListarTodosAcessos() {
            return base.Channel.ListarTodosAcessos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.AcessoModel>> ListarTodosAcessosAsync() {
            return base.Channel.ListarTodosAcessosAsync();
        }
        
        public Solicita.TG.UI.View.AcessoService.AcessoModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.AcessoModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public void AlterarSenha(string Usuario, string Senha) {
            base.Channel.AlterarSenha(Usuario, Senha);
        }
        
        public System.Threading.Tasks.Task AlterarSenhaAsync(string Usuario, string Senha) {
            return base.Channel.AlterarSenhaAsync(Usuario, Senha);
        }
        
        public Solicita.TG.UI.View.AcessoService.InfoDeLogon Login(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.Login(Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.InfoDeLogon> LoginAsync(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.LoginAsync(Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.TiposModel> ListarTipos() {
            return base.Channel.ListarTipos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.View.AcessoService.TiposModel>> ListarTiposAsync() {
            return base.Channel.ListarTiposAsync();
        }
        
        public Solicita.TG.UI.View.AcessoService.InfoDeLogon LogarComoALuno(string RA, string RG, string Senha) {
            return base.Channel.LogarComoALuno(RA, RG, Senha);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.View.AcessoService.InfoDeLogon> LogarComoALunoAsync(string RA, string RG, string Senha) {
            return base.Channel.LogarComoALunoAsync(RA, RG, Senha);
        }
        
        public bool RecuperarSenha(string RA, string RG, string Email) {
            return base.Channel.RecuperarSenha(RA, RG, Email);
        }
        
        public System.Threading.Tasks.Task<bool> RecuperarSenhaAsync(string RA, string RG, string Email) {
            return base.Channel.RecuperarSenhaAsync(RA, RG, Email);
        }
    }
}
