//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.CursoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.cursoService.Mo" +
        "delos")]
    [System.SerializableAttribute()]
    public partial class CursoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CursoService.ICursoService")]
    public interface ICursoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/CriarCurso", ReplyAction="http://tempuri.org/ICursoService/CriarCursoResponse")]
        System.Guid CriarCurso(string nome, System.Collections.Generic.List<string> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/CriarCurso", ReplyAction="http://tempuri.org/ICursoService/CriarCursoResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarCursoAsync(string nome, System.Collections.Generic.List<string> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Get", ReplyAction="http://tempuri.org/ICursoService/GetResponse")]
        Solicita.TG.UI.CursoService.CursoModel Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Get", ReplyAction="http://tempuri.org/ICursoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.CursoService.CursoModel> GetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/ListarTodas", ReplyAction="http://tempuri.org/ICursoService/ListarTodasResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.CursoService.CursoModel> ListarTodas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/ListarTodas", ReplyAction="http://tempuri.org/ICursoService/ListarTodasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.CursoService.CursoModel>> ListarTodasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Excluir", ReplyAction="http://tempuri.org/ICursoService/ExcluirResponse")]
        void Excluir(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Excluir", ReplyAction="http://tempuri.org/ICursoService/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Salvar", ReplyAction="http://tempuri.org/ICursoService/SalvarResponse")]
        void Salvar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/Salvar", ReplyAction="http://tempuri.org/ICursoService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/AlterarCurso", ReplyAction="http://tempuri.org/ICursoService/AlterarCursoResponse")]
        void AlterarCurso(System.Guid id, string nome, System.Collections.Generic.List<string> idDisciplinas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/AlterarCurso", ReplyAction="http://tempuri.org/ICursoService/AlterarCursoResponse")]
        System.Threading.Tasks.Task AlterarCursoAsync(System.Guid id, string nome, System.Collections.Generic.List<string> idDisciplinas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoServiceChannel : Solicita.TG.UI.CursoService.ICursoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.CursoService.ICursoService>, Solicita.TG.UI.CursoService.ICursoService {
        
        public CursoServiceClient() {
        }
        
        public CursoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarCurso(string nome, System.Collections.Generic.List<string> idDisciplinas) {
            return base.Channel.CriarCurso(nome, idDisciplinas);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarCursoAsync(string nome, System.Collections.Generic.List<string> idDisciplinas) {
            return base.Channel.CriarCursoAsync(nome, idDisciplinas);
        }
        
        public Solicita.TG.UI.CursoService.CursoModel Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.CursoService.CursoModel> GetAsync(System.Guid id) {
            return base.Channel.GetAsync(id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.CursoService.CursoModel> ListarTodas() {
            return base.Channel.ListarTodas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.CursoService.CursoModel>> ListarTodasAsync() {
            return base.Channel.ListarTodasAsync();
        }
        
        public void Excluir(System.Guid id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(System.Guid id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public void Salvar() {
            base.Channel.Salvar();
        }
        
        public System.Threading.Tasks.Task SalvarAsync() {
            return base.Channel.SalvarAsync();
        }
        
        public void AlterarCurso(System.Guid id, string nome, System.Collections.Generic.List<string> idDisciplinas) {
            base.Channel.AlterarCurso(id, nome, idDisciplinas);
        }
        
        public System.Threading.Tasks.Task AlterarCursoAsync(System.Guid id, string nome, System.Collections.Generic.List<string> idDisciplinas) {
            return base.Channel.AlterarCursoAsync(id, nome, idDisciplinas);
        }
    }
}
