//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.AlunoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
    [System.SerializableAttribute()]
    public partial class AlunoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.AlunoService.AlunoModel.MatriculaModel MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.AlunoService.AlunoModel.MatriculaModel Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RG {
            get {
                return this.RGField;
            }
            set {
                if ((object.ReferenceEquals(this.RGField, value) != true)) {
                    this.RGField = value;
                    this.RaisePropertyChanged("RG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AlunoModel.MatriculaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Aluno.Modelos")]
        [System.SerializableAttribute()]
        public partial class MatriculaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PeriodoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string RAField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string TurnoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Periodo {
                get {
                    return this.PeriodoField;
                }
                set {
                    if ((object.ReferenceEquals(this.PeriodoField, value) != true)) {
                        this.PeriodoField = value;
                        this.RaisePropertyChanged("Periodo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string RA {
                get {
                    return this.RAField;
                }
                set {
                    if ((object.ReferenceEquals(this.RAField, value) != true)) {
                        this.RAField = value;
                        this.RaisePropertyChanged("RA");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Turno {
                get {
                    return this.TurnoField;
                }
                set {
                    if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                        this.TurnoField = value;
                        this.RaisePropertyChanged("Turno");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlunoService.IAlunoService")]
    public interface IAlunoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/CriarAluno", ReplyAction="http://tempuri.org/IAlunoService/CriarAlunoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.AlunoService.MyServiceFault), Action="http://tempuri.org/IAlunoService/CriarAlunoMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        void CriarAluno(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/CriarAluno", ReplyAction="http://tempuri.org/IAlunoService/CriarAlunoResponse")]
        System.Threading.Tasks.Task CriarAlunoAsync(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Get", ReplyAction="http://tempuri.org/IAlunoService/GetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.AlunoService.MyServiceFault), Action="http://tempuri.org/IAlunoService/GetMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        Solicita.TG.UI.AlunoService.AlunoModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/Get", ReplyAction="http://tempuri.org/IAlunoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.AlunoService.AlunoModel> GetAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ListarTodosAlunos", ReplyAction="http://tempuri.org/IAlunoService/ListarTodosAlunosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.AlunoService.AlunoModel> ListarTodosAlunos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/ListarTodosAlunos", ReplyAction="http://tempuri.org/IAlunoService/ListarTodosAlunosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.AlunoService.AlunoModel>> ListarTodosAlunosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/AlterarAluno", ReplyAction="http://tempuri.org/IAlunoService/AlterarAlunoResponse")]
        void AlterarAluno(System.Guid Id, string Nome, string Sobrenome, int Periodo, int Turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlunoService/AlterarAluno", ReplyAction="http://tempuri.org/IAlunoService/AlterarAlunoResponse")]
        System.Threading.Tasks.Task AlterarAlunoAsync(System.Guid Id, string Nome, string Sobrenome, int Periodo, int Turno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlunoServiceChannel : Solicita.TG.UI.AlunoService.IAlunoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlunoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.AlunoService.IAlunoService>, Solicita.TG.UI.AlunoService.IAlunoService {
        
        public AlunoServiceClient() {
        }
        
        public AlunoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlunoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CriarAluno(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno) {
            base.Channel.CriarAluno(Nome, Sobrenome, RA, RG, Periodo, Turno);
        }
        
        public System.Threading.Tasks.Task CriarAlunoAsync(string Nome, string Sobrenome, string RA, string RG, int Periodo, int Turno) {
            return base.Channel.CriarAlunoAsync(Nome, Sobrenome, RA, RG, Periodo, Turno);
        }
        
        public Solicita.TG.UI.AlunoService.AlunoModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.AlunoService.AlunoModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.AlunoService.AlunoModel> ListarTodosAlunos() {
            return base.Channel.ListarTodosAlunos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.AlunoService.AlunoModel>> ListarTodosAlunosAsync() {
            return base.Channel.ListarTodosAlunosAsync();
        }
        
        public void AlterarAluno(System.Guid Id, string Nome, string Sobrenome, int Periodo, int Turno) {
            base.Channel.AlterarAluno(Id, Nome, Sobrenome, Periodo, Turno);
        }
        
        public System.Threading.Tasks.Task AlterarAlunoAsync(System.Guid Id, string Nome, string Sobrenome, int Periodo, int Turno) {
            return base.Channel.AlterarAlunoAsync(Id, Nome, Sobrenome, Periodo, Turno);
        }
    }
}
