//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.FuncionarioAcademicoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FuncionarioModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.FuncionarioAcad" +
        "emico.Modelos")]
    [System.SerializableAttribute()]
    public partial class FuncionarioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SobrenomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sobrenome {
            get {
                return this.SobrenomeField;
            }
            set {
                if ((object.ReferenceEquals(this.SobrenomeField, value) != true)) {
                    this.SobrenomeField = value;
                    this.RaisePropertyChanged("Sobrenome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FuncionarioAcademicoService.IFuncionarioAcademicoService")]
    public interface IFuncionarioAcademicoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/CriarFuncionario", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/CriarFuncionarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.FuncionarioAcademicoService.MyServiceFault), Action="http://tempuri.org/IFuncionarioAcademicoService/CriarFuncionarioMyServiceFaultFau" +
            "lt", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        System.Guid CriarFuncionario(string Nome, string Sobrenome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/CriarFuncionario", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/CriarFuncionarioResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarFuncionarioAsync(string Nome, string Sobrenome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/ListarTodosFuncionarios", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/ListarTodosFuncionariosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel> ListarTodosFuncionarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/ListarTodosFuncionarios", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/ListarTodosFuncionariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel>> ListarTodosFuncionariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/Get", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/GetResponse")]
        Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionarioAcademicoService/Get", ReplyAction="http://tempuri.org/IFuncionarioAcademicoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel> GetAsync(System.Guid Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFuncionarioAcademicoServiceChannel : Solicita.TG.UI.FuncionarioAcademicoService.IFuncionarioAcademicoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionarioAcademicoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.FuncionarioAcademicoService.IFuncionarioAcademicoService>, Solicita.TG.UI.FuncionarioAcademicoService.IFuncionarioAcademicoService {
        
        public FuncionarioAcademicoServiceClient() {
        }
        
        public FuncionarioAcademicoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionarioAcademicoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioAcademicoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioAcademicoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarFuncionario(string Nome, string Sobrenome) {
            return base.Channel.CriarFuncionario(Nome, Sobrenome);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarFuncionarioAsync(string Nome, string Sobrenome) {
            return base.Channel.CriarFuncionarioAsync(Nome, Sobrenome);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel> ListarTodosFuncionarios() {
            return base.Channel.ListarTodosFuncionarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel>> ListarTodosFuncionariosAsync() {
            return base.Channel.ListarTodosFuncionariosAsync();
        }
        
        public Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.FuncionarioAcademicoService.FuncionarioModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
    }
}
