//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.DisciplinaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisciplinaModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.DisciplinaServi" +
        "ce.Modelos")]
    [System.SerializableAttribute()]
    public partial class DisciplinaModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CargaHorariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CargaHoraria {
            get {
                return this.CargaHorariaField;
            }
            set {
                if ((this.CargaHorariaField.Equals(value) != true)) {
                    this.CargaHorariaField = value;
                    this.RaisePropertyChanged("CargaHoraria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DisciplinaService.IDisciplinaService")]
    public interface IDisciplinaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/CriarDisciplina", ReplyAction="http://tempuri.org/IDisciplinaService/CriarDisciplinaResponse")]
        System.Guid CriarDisciplina(string nome, int cargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/CriarDisciplina", ReplyAction="http://tempuri.org/IDisciplinaService/CriarDisciplinaResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarDisciplinaAsync(string nome, int cargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Get", ReplyAction="http://tempuri.org/IDisciplinaService/GetResponse")]
        Solicita.TG.UI.DisciplinaService.DisciplinaModel Get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Get", ReplyAction="http://tempuri.org/IDisciplinaService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.DisciplinaService.DisciplinaModel> GetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/ListarTodas", ReplyAction="http://tempuri.org/IDisciplinaService/ListarTodasResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.DisciplinaService.DisciplinaModel> ListarTodas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/ListarTodas", ReplyAction="http://tempuri.org/IDisciplinaService/ListarTodasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.DisciplinaService.DisciplinaModel>> ListarTodasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Excluir", ReplyAction="http://tempuri.org/IDisciplinaService/ExcluirResponse")]
        void Excluir(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Excluir", ReplyAction="http://tempuri.org/IDisciplinaService/ExcluirResponse")]
        System.Threading.Tasks.Task ExcluirAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Salvar", ReplyAction="http://tempuri.org/IDisciplinaService/SalvarResponse")]
        void Salvar(System.Guid id, string novoNome, int novaCargaHoraria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDisciplinaService/Salvar", ReplyAction="http://tempuri.org/IDisciplinaService/SalvarResponse")]
        System.Threading.Tasks.Task SalvarAsync(System.Guid id, string novoNome, int novaCargaHoraria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDisciplinaServiceChannel : Solicita.TG.UI.DisciplinaService.IDisciplinaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DisciplinaServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.DisciplinaService.IDisciplinaService>, Solicita.TG.UI.DisciplinaService.IDisciplinaService {
        
        public DisciplinaServiceClient() {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisciplinaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DisciplinaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarDisciplina(string nome, int cargaHoraria) {
            return base.Channel.CriarDisciplina(nome, cargaHoraria);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarDisciplinaAsync(string nome, int cargaHoraria) {
            return base.Channel.CriarDisciplinaAsync(nome, cargaHoraria);
        }
        
        public Solicita.TG.UI.DisciplinaService.DisciplinaModel Get(System.Guid id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.DisciplinaService.DisciplinaModel> GetAsync(System.Guid id) {
            return base.Channel.GetAsync(id);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.DisciplinaService.DisciplinaModel> ListarTodas() {
            return base.Channel.ListarTodas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.DisciplinaService.DisciplinaModel>> ListarTodasAsync() {
            return base.Channel.ListarTodasAsync();
        }
        
        public void Excluir(System.Guid id) {
            base.Channel.Excluir(id);
        }
        
        public System.Threading.Tasks.Task ExcluirAsync(System.Guid id) {
            return base.Channel.ExcluirAsync(id);
        }
        
        public void Salvar(System.Guid id, string novoNome, int novaCargaHoraria) {
            base.Channel.Salvar(id, novoNome, novaCargaHoraria);
        }
        
        public System.Threading.Tasks.Task SalvarAsync(System.Guid id, string novoNome, int novaCargaHoraria) {
            return base.Channel.SalvarAsync(id, novoNome, novaCargaHoraria);
        }
    }
}
