//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solicita.TG.UI.AcessoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
    [System.SerializableAttribute()]
    public partial class MyServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AcessoModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class AcessoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuario {
            get {
                return this.TipoDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeUsuarioField, value) != true)) {
                    this.TipoDeUsuarioField = value;
                    this.RaisePropertyChanged("TipoDeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AcessoModel.TipoDeUsuarioModel", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
        [System.SerializableAttribute()]
        public partial class TipoDeUsuarioModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NomeDoTipoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int TipoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string NomeDoTipo {
                get {
                    return this.NomeDoTipoField;
                }
                set {
                    if ((object.ReferenceEquals(this.NomeDoTipoField, value) != true)) {
                        this.NomeDoTipoField = value;
                        this.RaisePropertyChanged("NomeDoTipo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Tipo {
                get {
                    return this.TipoField;
                }
                set {
                    if ((this.TipoField.Equals(value) != true)) {
                        this.TipoField = value;
                        this.RaisePropertyChanged("Tipo");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoDeLogon", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os.Acesso.Modelos")]
    [System.SerializableAttribute()]
    public partial class InfoDeLogon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AcessoLiberadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeDoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Solicita.TG.UI.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcessoLiberado {
            get {
                return this.AcessoLiberadoField;
            }
            set {
                if ((this.AcessoLiberadoField.Equals(value) != true)) {
                    this.AcessoLiberadoField = value;
                    this.RaisePropertyChanged("AcessoLiberado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeDoUsuario {
            get {
                return this.NomeDoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeDoUsuarioField, value) != true)) {
                    this.NomeDoUsuarioField = value;
                    this.RaisePropertyChanged("NomeDoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Solicita.TG.UI.AcessoService.AcessoModel.TipoDeUsuarioModel TipoDeUsuario {
            get {
                return this.TipoDeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDeUsuarioField, value) != true)) {
                    this.TipoDeUsuarioField = value;
                    this.RaisePropertyChanged("TipoDeUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcessoService.IAcessoService")]
    public interface IAcessoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/CriarAcesso", ReplyAction="http://tempuri.org/IAcessoService/CriarAcessoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Solicita.TG.UI.AcessoService.MyServiceFault), Action="http://tempuri.org/IAcessoService/CriarAcessoMyServiceFaultFault", Name="MyServiceFault", Namespace="http://schemas.datacontract.org/2004/07/Solicita.TG.Servi%C3%A7os")]
        System.Guid CriarAcesso(string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/CriarAcesso", ReplyAction="http://tempuri.org/IAcessoService/CriarAcessoResponse")]
        System.Threading.Tasks.Task<System.Guid> CriarAcessoAsync(string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTodosAcessos", ReplyAction="http://tempuri.org/IAcessoService/ListarTodosAcessosResponse")]
        System.Collections.Generic.List<Solicita.TG.UI.AcessoService.AcessoModel> ListarTodosAcessos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/ListarTodosAcessos", ReplyAction="http://tempuri.org/IAcessoService/ListarTodosAcessosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.AcessoService.AcessoModel>> ListarTodosAcessosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Get", ReplyAction="http://tempuri.org/IAcessoService/GetResponse")]
        Solicita.TG.UI.AcessoService.AcessoModel Get(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Get", ReplyAction="http://tempuri.org/IAcessoService/GetResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.AcessoService.AcessoModel> GetAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/AlterarSenha", ReplyAction="http://tempuri.org/IAcessoService/AlterarSenhaResponse")]
        void AlterarSenha(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/AlterarSenha", ReplyAction="http://tempuri.org/IAcessoService/AlterarSenhaResponse")]
        System.Threading.Tasks.Task AlterarSenhaAsync(string Usuario, string Senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Login", ReplyAction="http://tempuri.org/IAcessoService/LoginResponse")]
        Solicita.TG.UI.AcessoService.InfoDeLogon Login(string Usuario, string Senha, int TipoDeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAcessoService/Login", ReplyAction="http://tempuri.org/IAcessoService/LoginResponse")]
        System.Threading.Tasks.Task<Solicita.TG.UI.AcessoService.InfoDeLogon> LoginAsync(string Usuario, string Senha, int TipoDeUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcessoServiceChannel : Solicita.TG.UI.AcessoService.IAcessoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcessoServiceClient : System.ServiceModel.ClientBase<Solicita.TG.UI.AcessoService.IAcessoService>, Solicita.TG.UI.AcessoService.IAcessoService {
        
        public AcessoServiceClient() {
        }
        
        public AcessoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcessoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcessoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcessoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CriarAcesso(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.CriarAcesso(Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CriarAcessoAsync(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.CriarAcessoAsync(Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Collections.Generic.List<Solicita.TG.UI.AcessoService.AcessoModel> ListarTodosAcessos() {
            return base.Channel.ListarTodosAcessos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Solicita.TG.UI.AcessoService.AcessoModel>> ListarTodosAcessosAsync() {
            return base.Channel.ListarTodosAcessosAsync();
        }
        
        public Solicita.TG.UI.AcessoService.AcessoModel Get(System.Guid Id) {
            return base.Channel.Get(Id);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.AcessoService.AcessoModel> GetAsync(System.Guid Id) {
            return base.Channel.GetAsync(Id);
        }
        
        public void AlterarSenha(string Usuario, string Senha) {
            base.Channel.AlterarSenha(Usuario, Senha);
        }
        
        public System.Threading.Tasks.Task AlterarSenhaAsync(string Usuario, string Senha) {
            return base.Channel.AlterarSenhaAsync(Usuario, Senha);
        }
        
        public Solicita.TG.UI.AcessoService.InfoDeLogon Login(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.Login(Usuario, Senha, TipoDeUsuario);
        }
        
        public System.Threading.Tasks.Task<Solicita.TG.UI.AcessoService.InfoDeLogon> LoginAsync(string Usuario, string Senha, int TipoDeUsuario) {
            return base.Channel.LoginAsync(Usuario, Senha, TipoDeUsuario);
        }
    }
}
